# Generated by Django 3.2.4 on 2021-06-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='할 일 제목', max_length=100)),
                ('content', models.TextField(help_text='할 일 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='할 일 생성 일자')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='할 일 수정 일자')),
                ('is_completed', models.BooleanField(default=False, help_text='할 일 완료 여부')),
            ],
        ),
    ]
